# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Format commit messages
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.20.0
    hooks:
      - id: commitlint
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: go-mod-tidy
        name: go mod tidy
        entry: bash -c 'go mod tidy'
        language: system
        pass_filenames: false
        types: [go]

      - id: goimports
        name: goimports
        entry: bash -c 'go install golang.org/x/tools/cmd/goimports@latest && goimports -w .'
        language: system
        types: [go]
        pass_filenames: false

      - id: gofumpt
        name: gofumpt
        entry: bash -c 'go install mvdan.cc/gofumpt@latest && gofumpt -w .'
        language: system
        types: [go]
        pass_filenames: false

      - id: golines
        name: golines
        entry: bash -c 'go install github.com/segmentio/golines@latest && golines -w .'
        language: system
        types: [go]
        pass_filenames: false

      - id: geminicommit
        name: Generate Commit Message with Gemini
        entry: geminicommit
        language: system
        stages: [prepare-commit-msg]
        always_run: true
        pass_filenames: false

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
