name: Debug Event

on:
  pull_request:
    branches: [ main, master ]
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  debug-event:
    name: Debug Event Trigger
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Print Event Details
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Action: ${{ github.event.action }}"
          echo "Base Branch: ${{ github.base_ref }}"
          echo "Repository: ${{ github.repository }}"
          echo "SHA: ${{ github.sha }}"
      - name: Print head ref (safe)
        run: |
          echo "GITHUB_HEAD_REF=$GITHUB_HEAD_REF"
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
