name: GoReleaser Dry Run

on:
  workflow_call:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no actual release)'
        type: boolean
        default: true
        required: true

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    outputs:
      artifacts: ${{ steps.run-goreleaser.outputs.artifacts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21'
          check-latest: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        id: run-goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: >-
            release
            --clean
            ${{ inputs.dry_run == true && '--skip-publish --skip-validate' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
