name: Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Install Go tools
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/segmentio/golines@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Run pre-commit
        run: pre-commit run --all-files
