name: Release

on:
  push:
    tags:
      - 'v*'
  # Add manual trigger for testing
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no actual release)'
        type: boolean
        default: true
        required: true

permissions:
  contents: write
  packages: write
  id-token: write # needed for SLSA provenance

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    outputs:
      artifacts: ${{ steps.run-goreleaser.outputs.artifacts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Add this step to create a fake tag for testing with workflow_dispatch
      - name: Create testing tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config --local user.email "test@example.com"
          git config --local user.name "Test Release Bot"
          # Create a temporary local tag for testing
          echo "RELEASE_TAG=v0.0.0-test-$(date +%s)" >> $GITHUB_ENV
          git tag $RELEASE_TAG

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21'
          check-latest: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Run GoReleaser
      - name: Run GoReleaser
        id: run-goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: >-
            release
            --clean
            ${{ github.event.inputs.dry_run == 'true' && '--skip-publish' || '' }}
            ${{ github.event.inputs.dry_run == 'true' && '--skip-validate' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Clean up test tag so we don't pollute the repo
      - name: Clean up test tag
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.dry_run == 'true'
        run: |
          git tag -d $RELEASE_TAG || true

  # Include the rest of your jobs (goreleaser-hashes, provenance, verification)
  # with conditional execution if not in dry-run mode
  goreleaser-hashes:
    runs-on: ubuntu-latest
    needs: [goreleaser]
    # Skip this job if running in dry-run mode
    if: github.event.inputs.dry_run != 'true'
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - name: Generate hashes for provenance
        id: hash
        env:
          ARTIFACTS: "${{ needs.goreleaser.outputs.artifacts }}"
        run: |
          echo "hashes=$(echo $ARTIFACTS | jq -r '.[] | select(.type=="Binary") | .path' | sha256sum | base64 -w0)" >> $GITHUB_OUTPUT

  # SLSA provenance generation - only run if not in dry-run mode
  provenance:
    needs: [goreleaser-hashes]
    if: github.event.inputs.dry_run != 'true'
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    with:
      base64-subjects: "${{ needs.goreleaser-hashes.outputs.hashes }}"
      upload-assets: true

  # Optional verification step - only run if not in dry-run mode
  verification:
    needs: [goreleaser, provenance]
    if: github.event.inputs.dry_run != 'true'
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Install SLSA verifier
        uses: slsa-framework/slsa-verifier/actions/installer@v2.7.0

      - name: Download assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROVENANCE: "${{ needs.provenance.outputs.provenance-name }}"
        run: |
          set -euo pipefail
          gh -R "$GITHUB_REPOSITORY" release download "$GITHUB_REF_NAME" -p "*.tar.gz"
          gh -R "$GITHUB_REPOSITORY" release download "$GITHUB_REF_NAME" -p "$PROVENANCE"

      - name: Verify assets
        env:
          CHECKSUMS: ${{ needs.goreleaser-hashes.outputs.hashes }}
          PROVENANCE: "${{ needs.provenance.outputs.provenance-name }}"
        run: |
          set -euo pipefail
          checksums=$(echo "$CHECKSUMS" | base64 -d)
          slsa-verifier verify-artifact \
            --provenance-path "$PROVENANCE" \
            --source-uri "github.com/$GITHUB_REPOSITORY" \
            --source-tag "$GITHUB_REF_NAME"
