name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  id-token: write # needed for SLSA provenance

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    outputs:
      artifacts: ${{ steps.run-goreleaser.outputs.artifacts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21'
          check-latest: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Optional: If you're using GPG signing
      # - name: Import GPG key
      #   uses: crazy-max/ghaction-import-gpg@v6
      #   id: import_gpg
      #   with:
      #     gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.PASSPHRASE }}

      - name: Run GoReleaser
        id: run-goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # If using GPG signing:
          # GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}

  # Updated SLSA provenance generation for Level 3
  goreleaser-hashes:
    runs-on: ubuntu-latest
    needs: [goreleaser]
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - name: Generate hashes for provenance
        id: hash
        env:
          ARTIFACTS: "${{ needs.goreleaser.outputs.artifacts }}"
        run: |
          echo "hashes=$(echo $ARTIFACTS | jq -r '.[] | select(.type=="Binary") | .path' | sha256sum | base64 -w0)" >> $GITHUB_OUTPUT

  # SLSA provenance generation
  provenance:
    needs: [goreleaser-hashes]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    with:
      base64-subjects: "${{ needs.goreleaser-hashes.outputs.hashes }}"
      upload-assets: true

  # Optional verification step
  verification:
    needs: [goreleaser, provenance]
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Install SLSA verifier
        uses: slsa-framework/slsa-verifier/actions/installer@v2.7.0

      - name: Download assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROVENANCE: "${{ needs.provenance.outputs.provenance-name }}"
        run: |
          set -euo pipefail
          gh -R "$GITHUB_REPOSITORY" release download "$GITHUB_REF_NAME" -p "*.tar.gz"
          gh -R "$GITHUB_REPOSITORY" release download "$GITHUB_REF_NAME" -p "$PROVENANCE"

      - name: Verify assets
        env:
          CHECKSUMS: ${{ needs.goreleaser-hashes.outputs.hashes }}
          PROVENANCE: "${{ needs.provenance.outputs.provenance-name }}"
        run: |
          set -euo pipefail
          checksums=$(echo "$CHECKSUMS" | base64 -d)
          slsa-verifier verify-artifact \
            --provenance-path "$PROVENANCE" \
            --source-uri "github.com/$GITHUB_REPOSITORY" \
            --source-tag "$GITHUB_REF_NAME"
